### ISSUE TITLE
Automate testing

### ISSUE THREAD

**Issue by Lasped13** [BerkayDur/Kelpie-LNHM-Botanical-project#6]
Create a GitHub action to automated the testing process to ensure that pushes with passing tests can only be merged. This will help ensure that our `main` branch is always in working condition.

- [ ] Set-up Github action
- [ ] Verify this works through testing
- [ ] Confer with team to determine a minimum-testing score
- [ ] Prettify this by adding a badge to the branch, showing the proportion of passing tests.

**Comment by BerkayDur** [comment]
> Create a GitHub action to automated the testing process to ensure that pushes with passing tests can only be merged. This will help ensure that our `main` branch is always in working condition.

- [] Set-up Github action
- [] Verify this works through testing
- [] Confer with team to determine a minimum-testing score
- [] Prettify this by adding a badge to the branch, showing the proportion of passing tests.
